# Alertmanager告警配置
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@luckee-dao.com'
  smtp_auth_username: 'alerts@luckee-dao.com'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: 'database'
      receiver: 'database-alerts'
    - match:
        service: 'blockchain'
      receiver: 'blockchain-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://webhook:5001/'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@luckee-dao.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
    webhook_configs:
      - url: 'http://webhook:5001/critical'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@luckee-dao.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@luckee-dao.com'
        subject: '[DATABASE] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

  - name: 'blockchain-alerts'
    email_configs:
      - to: 'blockchain@luckee-dao.com'
        subject: '[BLOCKCHAIN] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
